## File initially generated by createOverlay
## and then modified manually.
## Some hints for manual modifications are in the file,
## but the full doc is on nixos / nix packages website:
## https://nixos.org/manual/nixpkgs/stable/#sec-language-coq

{ lib, mkCoqDerivation, coq
  , mathcomp, mathcomp-analysis, mathcomp-algebra-tactics
  , rocqnavi
  , version ? null }:

with lib; mkCoqDerivation {
  pname = "QLLib";
  owner = "QLLib";
  repo = "QLLib";

  inherit version;
## The `defaultVersion` attribute is important for nixpkgs but can be kept unchanged
## for local usage since it will be ignored locally if
## - this derivation corresponds to the main attribute,
## - or its version is overridden (by a branch, PR, url or path) in `.nix/config.nix`.
## There is no tagged release of QLLib yet, so there is no default
## version to pick: the toolbox always overrides it with the local sources
## (see `attribute = "QLLib"` in `.nix/config.nix`).
  defaultVersion = with versions; switch coq.coq-version [
    ## once a release exists, declare it below and map it here, e.g.
    # { case = range "9.0" "9.1"; out = "1.0.0"; }
  ] null;

  ## Declare existing releases
  ## leave sha256 empty at first and then copy paste
  ## the resulting sha given by the error message
  # release."1.0.0".sha256 = "";

  propagatedBuildInputs = [
    mathcomp
    mathcomp-analysis
    mathcomp-algebra-tactics
  ];

  ## Not needed to build the library, only to run `make doc`.  Declaring it
  ## here is what puts `rocqnavi` on the `nix-shell` PATH: coq-nix-toolbox
  ## builds the shell by overriding this derivation (see `nativeBuildInputs`
  ## in the toolbox's default.nix).
  nativeBuildInputs = [ rocqnavi ];

  meta = {
    description = "Formalisation of the Differentiable Logics in Rocq with MathComp";
    homepage = "https://github.com/Janis-Bai/QLLib";
    license = licenses.mit;
  };
}
